// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/categories.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/categories.put').default>>>>
    }
    '/api/admin/content': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/content.put').default>>>>
    }
    '/api/admin/discounts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/discounts.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/discounts.post').default>>>>
    }
    '/api/admin/discounts/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/discounts/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/discounts/[id].put').default>>>>
    }
    '/api/admin/featured': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/featured.put').default>>>>
    }
    '/api/admin/images': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/images.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/images.post').default>>>>
    }
    '/api/admin/images/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/images/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/images/[id].put').default>>>>
    }
    '/api/admin/images/:id/dark': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/images/[id]/dark.put').default>>>>
    }
    '/api/admin/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/me.get').default>>>>
    }
    '/api/admin/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products.post').default>>>>
    }
    '/api/admin/products/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products/[id].put').default>>>>
    }
    '/api/admin/promo-codes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/promo-codes.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/promo-codes.post').default>>>>
    }
    '/api/admin/promo-codes/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/promo-codes/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/promo-codes/[id].put').default>>>>
    }
    '/api/admin/seo-audit': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/seo-audit.get').default>>>>
    }
    '/api/admin/universes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/universes.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/universes.put').default>>>>
    }
    '/api/admin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users.get').default>>>>
    }
    '/api/admin/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].put').default>>>>
    }
    '/api/admin/users/:id/password-reset': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id]/password-reset.post').default>>>>
    }
    '/api/admin/users/demo': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/demo.post').default>>>>
    }
    '/api/auth/change-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/change-password.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/password-code/confirm': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/password-code/confirm.post').default>>>>
    }
    '/api/auth/password-code/request': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/password-code/request.post').default>>>>
    }
    '/api/auth/profile': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/profile.put').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories.get').default>>>>
    }
    '/api/checkout/paypal': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/checkout/paypal.post').default>>>>
    }
    '/api/checkout/paypal/capture': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/checkout/paypal/capture.get').default>>>>
    }
    '/api/checkout/stripe': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/checkout/stripe.post').default>>>>
    }
    '/api/contact/attachment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact/attachment.post').default>>>>
    }
    '/api/contact/attachment/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact/attachment/[id].delete').default>>>>
    }
    '/api/contact/send-code': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact/send-code.post').default>>>>
    }
    '/api/contact/send': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact/send.post').default>>>>
    }
    '/api/content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content.get').default>>>>
    }
    '/api/images/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/[id].get').default>>>>
    }
    '/api/products/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[slug].get').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.get').default>>>>
    }
    '/api/promo-codes/validate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/promo-codes/validate.post').default>>>>
    }
    '/api/universes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/universes.get').default>>>>
    }
    '/api/webhooks/stripe': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhooks/stripe.post').default>>>>
    }
    '/images/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/images/[id].get').default>>>>
    }
    '/llms.txt': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/llms.txt.get').default>>>>
    }
    '/robots.txt': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/robots.txt.get').default>>>>
    }
    '/sitemap.xml': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sitemap.xml.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}